### ISSUE TITLE
In this paper, it say ". Our view generator includes both augmentations of node dropping and attribute masking, but it is much more flexible since both two augmentations can be simultaneously employed in a node-wise manner, without the need of tuning the “aug ratio”." But I didn't find the model how to mask attribute and tuning the "aug ratio" in the code. Could you please tell me which part of the code of these two functions?Question

### ISSUE THREAD

**Issue by SeaSpring17** [Somedaywilldo/AutoGCL#2]
[Uploading image.png…v]()

**Comment by Somedaywilldo** [comment]
Hi SeaSpring17,
I'm sorry for this problem, I've updated the code, I believe now you can achieve the node attribute masking through the flag "args.add_mask" in semi-supervised/main.py, the corresponding implementation is [here](https://github.com/Somedaywilldo/AutoGCL/blob/3d11b967a539e0d59cd3a33e8f170c31c8c32cfa/view_generator.py#L298). But I need to mention that enabling this function may not always be helpful to the specific tasks, I still find node dropping is most effective argumentation in our experiments, but this is a demonstration that our framework can support node attribute masking, maybe our exploration on this part is not enough, hope you find this helpful, thanks.
Sincerely,
Yihang
