### ISSUE TITLE
抱歉，并未找到如何调节aug_ratio的模块，但是找到了这个代码，调节aug_ratio是靠随机生成的吗

### ISSUE THREAD

**Issue by radium1234** [Somedaywilldo/AutoGCL#3]
augs.py 109行代码如下，
    def forward(self, data):
            self.aug = np.random.randint(4)
            if self.aug == 0:
                # print("node drop")
                data = NodeDrop(data, self.aug_ratio)
            elif self.aug == 1:
                # print("subgraph")
                data = Subgraph(data, self.aug_ratio)
            elif self.aug == 2:
                # print("edge perturb")
                data = EdgePerturb(data, self.aug_ratio)
            elif self.aug == 3:
                # print("attr mask")
                data = AttrMask(data, self.aug_ratio)
            else:
                print('sample augmentation error')
                assert False
            return data

**Comment by Somedaywilldo** [comment]
AutoGCL是不需要调节aug_ratio的，你这部分是我复现GraphCL的代码

**Comment by radium1234** [comment]
> 

抱歉，谢谢

**Comment by Somedaywilldo** [comment]
主要的code在view_generator.py里
